services:
  padenc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: padenc-api
    ports:
      - "8080:8080"
    environment:
      - STATION_NAME=Test Station
      - DEFAULT_STATION_IMAGE=/tests/mock/station.jpg
      - RUST_LOG=info
      - API_KEY=your_secret_api_key_here
    volumes:
      - ./data:/data
    restart: unless-stopped
